### ISSUE TITLE
Add GitHub Pages for this project

### ISSUE THREAD

**Issue by bugwelle** [mbeutel/CMakeshift#11]
Hi,

it would be great to have the documentation (`make sphinx`) on a gh-pages branch.
That way, GitHub hosts the documentation and it is easily linked to.

I use the same for some of my projects and have a simplistic script to automate updating the branch:

 - Update script: https://github.com/mediaelch/mediaelch-doc/blob/master/update_github_pages.sh

**Comment by mbeutel** [comment]
Thank you. That would be a reasonable thing to do if we were to proceed with Sphinx. I haven't quite made up my mind yet but I think I'd rather shun the extra complexity and do away with Sphinx in favor of plain and simple Markdown documentation as for [slowmath](https://mbeutel.github.io/slowmath/).

**Comment by bugwelle** [comment]
That would be great as well. :smile: 

I'd go the Sphinx way for this repository simply because it's what CMake itself does for their documentation. :)
