### ISSUE TITLE
CUDA device invisible in debug build

### ISSUE THREAD

**Issue by codecircuit** [mbeutel/CMakeshift#5]
You have a C++ library which uses CMakeshift to configure the compile settings with:

```cmake
# compiler settings
include(CMakeshift/TargetCompileSettings)
cmakeshift_target_compile_settings(mycpplib
    PRIVATE
        default
	diagnostics
	$<$<CONFIG:Debug>:runtime-checks>
)
```

and another CUDA executable which links against that library:

```cmake
add_executable(cuda_executable ...)
target_link_libraries(cuda_executable
mycpplib::mycpplib
)
```

If this executable is build with `-DCMAKE_BUILD_TYPE=Debug` no CUDA device is found any more. This is caused by `runtime-checks` in the CMakeshift compile settings. If no runtime checks are activated everything works fine.

**Comment by mbeutel** [comment]
Fixed by https://github.com/mbeutel/CMakeshift/commit/58804a08177db202796e8eaaa29d59a007b844b4 . This was a follow-up error of #4.
